### ISSUE TITLE
"Pinning..." forever at 98% in "My Private Docs"

### ISSUE THREAD

**Issue by sircotra** [vasa-develop/ipfscloud#23]
After setting the password ad uploaded a file in "My Private Docs", the loader box show "Pinning..." forever at 98%

**Comment by vasa-develop** [comment]
Hi @argfa 

This happens when the ipfs nodes are not available. If you encounter this issue, just wait for a few minutes and try again.

In order to address this issue, I am working on a robust platform which leverages IPFS Cluster to orchetrate a large number of nodes. You can follow the discussion [**here**](https://discuss.ipfs.io/t/community-discussion-ipfscloud-v2-0-draft/5420)

Cheers,
Vaibhav
